baseURL = 'https://links.rmhogervorst.nl/'
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "cupper-hugo-theme"
title = 'An overview of links'

[params]
    description = "A link blog or linklog that enables me to keep track of resources on the web."
    dateFormat= "2006-01-02 Monday"
    katex = true
    hideHeaderLinks = false
    search = true
    showThemeSwitcher = true
    defaultDarkTheme = false
    moveFooterToHeader = false

[taxonomies]
   tag = 'tags'
   linktype = 'linktypes'
   difficulty = 'difficulties'
   author = 'authors'

[permalinks]
  post = "/:filename/"

[outputs]
   home = [ "HTML", "JSON" ]

[[menu.nav]]
    name = "home"
    url = "/post/"
    weight = 1
[[menu.nav]]
    name = "tags"
    url = "/tags/"
    weight = 4
[[menu.nav]]
    name = "RSS"
    url = "/post/index.xml"
    weigth = 4
[[menu.nav]]
    name = "mastodon"
    url = "https://mastodon.world/@rmhogervorst"
    weigth = 2
[[menu.nav]]
    name = "blog"
    url = "https://blog.rmhogervorst.nl"
    weigth = 2
